apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
type: Opaque
data:
  # Use your own token and copy this file to ../bs-secret.local.yaml
  GITHUB_TOKEN: <Base64 encoded GitHub PAT>
  # https://github.com/settings/apps/peakscale-backstage
  AUTH_GITHUB_CLIENT_SECRET: <Base64 encoded GitHub App Client Secret>
